# main configuration file

# updated by ...: Loreto Notarantonio
# Date .........: 21-04-2025 19.03.16




# system_variables: !include system_variables.lnk.yaml#system_envars

main:



excel:
    # !include devices_DBase.lnk.yaml
    # !include "${HOME}/lnProfile/devicesDB/${DB_VERSION_DIR}/conf/devices_DBTable.yaml"
    # excel_filename: "${HOME}/lnProfile/devicesDB/DevicesV003/devicesDB.ods"
    # excel_filename: "${HOME}/ext_disk/Filu/Personali/Loreto/Office/Excel/Varie/Oliviero legna2024.xlsx"
    # excel_filename: "/media/loreto/LnDisk_SD_ext4/Filu/GIT-REPO/Python/stefanoGirini/data/export_contratti.xls"
    sheet:
        name: Contratti
        valid_columns:
            - SPEEDY_CTR_ID
            - AGENTE
            - PARTNER
            - PRODOTTO
            - ESITO

    esiti:
        exclude:
            - doppia prenotazione
            - ko < 12 mesi

        totale:
            include: all

        confermato:
            include:
                - confermato

        attivazione:
            include:
                - attivazione
        back:
            include:
                - Attesa
                - Prenotato
                - Gestito
                - NonConforme
                - "In lavorazione"
                - Accettato




