# main configuration file

# updated by ...: Loreto Notarantonio
# Date .........: 27-04-2025 17.17.58




# system_variables: !include system_variables.lnk.yaml#system_envars

___templates:
    ___resultStruct: &RESULT_STRUCTURE
            - Partner
            - Totale
            - Confermati
            - In attivazione
            - Back
            - RID
            - xxxx




main:

StrutturaAziendale_sample:
    Direttore:
        Area Manager:
            Manager Plus:
                Manager:
                    Team Manager:
                        Agente:
                            partner:
                              - totale
                              - conferma
                              - in Attivazione
                              - Back




StrutturaAziendale:
    !include_merge [
                    "../data/direttore_Cesarino.yaml",
                    "../data/direttore_Dibilio.yaml",
                    "../data/direttore_Chiaravallotti.yaml",
                    "../data/direttore_Guerriero.yaml"
                    ]



excel:
    # !include devices_DBase.lnk.yaml
    # !include "${HOME}/lnProfile/devicesDB/${DB_VERSION_DIR}/conf/devices_DBTable.yaml"
    # excel_filename: "${HOME}/lnProfile/devicesDB/DevicesV003/devicesDB.ods"
    # excel_filename: "${HOME}/ext_disk/Filu/Personali/Loreto/Office/Excel/Varie/Oliviero legna2024.xlsx"
    # excel_filename: "/media/loreto/LnDisk_SD_ext4/Filu/GIT-REPO/Python/stefanoGirini/data/export_contratti.xls"

    # verranno creati tanti fogli con qhete colonne a scalare
    output_sheet:
        colonne_gerarchia:
            - Direttore
            - Area Manager
            - Manager Plus
            - Manager
            - Team Manager
            - Agente

        # saranno presenti in tutti i fogli con i dati sommati all'ultimo livello visualizzato nelle colonne precedenti
        colonne_dati:
            *RESULT_STRUCTURE



    source_sheet:
        name: Contratti
        columns_to_be_extracted:
            - SPEEDY_CTR_ID
            - AGENTE
            - PARTNER
            - PRODOTTO
            - ESITO

    # -----------------------------------------------------------
    # - keywords da verificare all'interno del campo ESITO
    # - per permettere la catalogazione corretta dei contratti
    # -----------------------------------------------------------
    esito_keywords:
        exclude:
            - doppia prenotazione
            - ko < 12 mesi

        totale:
            include: all

        confermato:
            include:
                - confermato

        attivazione:
            include:
                - attivazione
        back:
            include:
                - Attesa
                - Prenotato
                - Gestito
                - NonConforme
                - "In lavorazione"
                - Accettato




