# main configuration file

# updated by ...: Loreto Notarantonio
# Date .........: 01-07-2025 10.50.28




# system_variables: !include system_variables.lnk.yaml#system_envars

___templates:
    ___resultStruct: &RESULT_STRUCTURE
            - Partner
            - Processati            # - tutti i record presenti nel file contratti
            - Excluded
            - Inseriti
            - Scartati
            - Totale
            - Confermati
            - In attivazione
            - Back
            - RID
            - RID%
            - VAS
            - VAS%
            - SIM
            - TV
            # - xxxx




main:

# StrutturaAziendale_sample:
#     Direttore:
#         Area Manager:
#             Manager Plus:
#                 Manager:
#                     Team Manager:
#                         Agente:
#                             partner:
#                               - totale
#                               - conferma
#                               - in Attivazione
#                               - Back




StrutturaAziendale:
    !include_merge [
                    "../data/direttore_Cesarino.yaml",
                    "../data/direttore_Dibilio.yaml",
                    "../data/direttore_Chiaravallotti.yaml",
                    "../data/direttore_Guerriero.yaml"
                    ]


working_files:
    agents_data:           "data_output/agents_data.yaml"
    agents_results:        "data_output/agents_results.yaml"
    contratti_preprocess:  "data_output/contratti_preprocess.yaml"
    contratti_dettagliati: "data_output/contratti_dettagliati.yaml"
    agenti_discrepanti:    "data_output/agenti_discrepanti.yaml"
    struttura_aziendale:   "data_output/struttura_aziendale_input.yaml"


excel:
    # !include devices_DBase.lnk.yaml
    # !include "${HOME}/lnProfile/devicesDB/${DB_VERSION_DIR}/conf/devices_DBTable.yaml"
    # excel_filename: "${HOME}/lnProfile/devicesDB/DevicesV003/devicesDB.ods"
    # excel_filename: "${HOME}/ext_disk/Filu/Personali/Loreto/Office/Excel/Varie/Oliviero legna2024.xlsx"
    # excel_filename: "/media/loreto/LnDisk_SD_ext4/Filu/GIT-REPO/Python/stefanoGirini/data/export_contratti.xls"

    # verranno creati tanti fogli con qhete colonne a scalare
    output_sheet:
        colonne_gerarchia:
            - Direttore
            - Area Manager
            - Manager Plus
            - Manager
            - Team Manager
            - Agente

        # saranno presenti in tutti i fogli con i dati sommati all'ultimo livello visualizzato nelle colonne precedenti
        colonne_dati:
            *RESULT_STRUCTURE


    source_sheet:
        name: Contratti
        columns_to_be_extracted:
            - SPEEDY_CTR_ID
            - AGENTE
            - PARTNER
            - PRODOTTO
            - ESITO

    # -----------------------------------------------------------
    # - keywords se presenti all'interno del campo ESITO
    # - per permettere la catalogazione corretta dei contratti
    # -----------------------------------------------------------
    esito_keywords:

        # - se trovate il record verrà escluso
        exclude:
            - doppia prenotazione
            - ko < 12 mesi

        # - se trovate il record verrà contato come confermato
        confermato:
            - confermato

        # - se trovate il record verrà contato come "in attivazione"
        attivazione:
            - in attivazione

        # - se trovate il record verrà contato come "back"
        back:
            - Attesa
            - Gestito
            - Non Conforme
            - Prenotato
            - lavorazione
            - Accettato



    # -----------------------------------------------------------
    # - keywords se presenti all'interno del campo PRODOTTO
    # - il campo potrebbe essere contato in più di una colonna
    # -----------------------------------------------------------
    prodotto_keywords:
        # - se trovate il record verrà contato nei rid
        rid:
            - rid

        vas:
            - vas

        sim:
            - sim
            - mobile

        tv:
            - "Tim Vision"
            - "Tim Gold"
            - "Tim Disney"
            - "Tim Calcio"
            - "Tim Intrattenimento"
            - "Tim Netflix"
            - "Tim Mobile"






